import Vue from "vue";

import AreaLink from "@/modules/competitions/components/links/AreaLink";
import AreasLink from "@/modules/competitions/components/links/AreasLink";
import CompetitionLink from "@/modules/competitions/components/links/CompetitionLink";
import CompetitionsLink from "@/modules/competitions/components/links/CompetitionsLink";
import CreateAreaLink from "@/modules/competitions/components/links/CreateAreaLink";
import CreateCategoryLink from "@/modules/competitions/components/links/CreateCategoryLink";
import CreateDisciplineLink from "@/modules/competitions/components/links/CreateDisciplineLink";
import CreateGroupLink from "@/modules/competitions/components/links/CreateGroupLink";
import DisciplineLink from "@/modules/competitions/components/links/DisciplineLink";
import DisciplinesLink from "@/modules/competitions/components/links/DisciplinesLink";
import GroupsLink from "@/modules/competitions/components/links/GroupsLink";
import ManageAreaLink from "@/modules/competitions/components/links/ManageAreaLink";
import ManageCategoryLink from "@/modules/competitions/components/links/ManageCategoryLink";
import ManageCompetitionLink from "@/modules/competitions/components/links/ManageCompetitionLink";
import ManageCompetitionsLink from "@/modules/competitions/components/links/ManageCompetitionsLink";
import ManageDisciplineLink from "@/modules/competitions/components/links/ManageDisciplineLink";
import ManageGroupLink from "@/modules/competitions/components/links/ManageGroupLink";

Vue.component("AreaLink", AreaLink);
Vue.component("AreasLink", AreasLink);
Vue.component("CompetitionLink", CompetitionLink);
Vue.component("CompetitionsLink", CompetitionsLink);
Vue.component("CreateAreaLink", CreateAreaLink);
Vue.component("CreateCategoryLink", CreateCategoryLink);
Vue.component("CreateDisciplineLink", CreateDisciplineLink);
Vue.component("CreateGroupLink", CreateGroupLink);
Vue.component("DisciplineLink", DisciplineLink);
Vue.component("DisciplinesLink", DisciplinesLink);
Vue.component("GroupsLink", GroupsLink);
Vue.component("ManageAreaLink", ManageAreaLink);
Vue.component("ManageCategoryLink", ManageCategoryLink);
Vue.component("ManageCompetitionLink", ManageCompetitionLink);
Vue.component("ManageCompetitionsLink", ManageCompetitionsLink);
Vue.component("ManageDisciplineLink", ManageDisciplineLink);
Vue.component("ManageGroupLink", ManageGroupLink);
