import Vue from "vue";

import AreasLink from "@/modules/competitions/components/links/AreasLink";
import CompetitionLink from "@/modules/competitions/components/links/CompetitionLink";
import CompetitionsLink from "@/modules/competitions/components/links/CompetitionsLink.vue";
import CreateDisciplineLink from "@/modules/competitions/components/links/CreateDisciplineLink.vue";
import DisciplineLink from "@/modules/competitions/components/links/DisciplineLink.vue";
import DisciplinesLink from "@/modules/competitions/components/links/DisciplinesLink.vue";
import GroupsLink from "@/modules/competitions/components/links/GroupsLink.vue";
import ManageCompetitionLink from "@/modules/competitions/components/links/ManageCompetitionLink";
import ManageCompetitionsLink from "@/modules/competitions/components/links/ManageCompetitionsLink.vue";
import ManageDisciplineLink from "@/modules/competitions/components/links/ManageDisciplineLink.vue";
import ManageGroupLink from "@/modules/competitions/components/links/ManageGroupLink.vue";
import CreateGroupLink from "@/modules/competitions/components/links/CreateGroupLink.vue";
import ManageCategoryLink from "@/modules/competitions/components/links/ManageCategoryLink.vue";
import CreateCategoryLink from "@/modules/competitions/components/links/CreateCategoryLink.vue";

Vue.component("AreasLink", AreasLink);
Vue.component("CompetitionLink", CompetitionLink);
Vue.component("CompetitionsLink", CompetitionsLink);
Vue.component("CreateDisciplineLink", CreateDisciplineLink);
Vue.component("DisciplineLink", DisciplineLink);
Vue.component("DisciplinesLink", DisciplinesLink);
Vue.component("GroupsLink", GroupsLink);
Vue.component("ManageCompetitionLink", ManageCompetitionLink);
Vue.component("ManageCompetitionsLink", ManageCompetitionsLink);
Vue.component("ManageDisciplineLink", ManageDisciplineLink);
Vue.component("ManageGroupLink", ManageGroupLink);
Vue.component("CreateGroupLink", CreateGroupLink);
Vue.component("ManageCategoryLink", ManageCategoryLink);
Vue.component("CreateCategoryLink", CreateCategoryLink);
